### ISSUE TITLE
Rescript users section

### ISSUE THREAD

**Issue by amiralies** [rescript-association/rescript-lang.org#108]
Should we have a section showing companies/projects which are using rescript like what we had in old bucklescript and reason website?

**Comment by ryyppy** [comment]
yes we should, but first we need our users to actually migrate to the newest ReScript version + syntax before we can effectively go out advertising industrial usage

**Comment by bdunn313** [comment]
As a sidenote, my company has successfully ported! We'd love to get our logo up there when we can bring a few people along with us. DM me if you are on the fence and want to talk shop on challenges. Full disclosure, we're hybrid TS / RES now, we are still mid-port of the entire codebase and being pragmatic about it.

**Comment by ryyppy** [comment]
@bdunn313 good to hear! definitely interested in detailed stories on how companies use ReScript in their products. I will come back to you when we are shaping up the landing page content, if this is fine?

**Comment by bdunn313** [comment]
Sounds good!

**Comment by ryyppy** [comment]
@bdunn313 Landing page is done now, so in case you are still interested (and using actual ReScript + its syntax in production) you can send me your svg logo along the way so we can add it to the page 😃

**Comment by noverby** [comment]
@ryyppy My company @aivero is also using ReScript in production, are you interested in more companies on the landing page?

**Comment by ryyppy** [comment]
@noverby definitely! I'll need to set me some time to finally add all the pending requests to the website.
You can either send a PR, or create a ticket with your svg (black / white, or ideally already in the same color as the other listed logos) and I will try to add it with all the other logos.

**Comment by noverby** [comment]
@ryyppy Nice, I have sent a PR and thanks! PR: #478

**Comment by ryyppy** [comment]
@bdunn313 in case you want your logo displayed on our front page, just follow these instructions (it's pretty straight forward): https://github.com/rescript-association/rescript-lang.org#how-to-add-your-company-logo-to-our-front-page

**Comment by ryyppy** [comment]
I will close this, since we now feature a "Users of ReScript" section.
