### ISSUE TITLE
missing docs for record renaming

### ISSUE THREAD

**Issue by bobzhang** [rescript-association/rescript-lang.org#189]
```res
type t = {
  @as("X") x: int,
  @as("Y") y: string,
}
```
and a special case for encoding array
```res
type t = {
  @as("0") x : int,
  @as("1") y : int
}
```

**Comment by ryyppy** [comment]
huh? i swear this was in the docs... will add that back.

**Comment by Minnozz** [comment]
It is mentioned here: https://rescript-lang.org/syntax-lookup#as-decorator
```res
type action = {
  @as("type") type_: string
}
```

The references link to [Constrain Arguments Better](https://rescript-lang.org/docs/manual/latest/bind-to-js-function#constrain-arguments-better) and [Fixed Arguments](https://rescript-lang.org/docs/manual/latest/bind-to-js-function#fixed-arguments).

It is not mentioned at [Bind Using ReScript Record](https://rescript-lang.org/docs/manual/latest/bind-to-js-object#bind-using-rescript-record), which is where I would expect it too.
