### ISSUE TITLE
Add available warning numbers for @@warning()

### ISSUE THREAD

**Issue by ryyppy** [rescript-association/rescript-lang.org#190]
We already map our warnings numbers in our playground (check the "Settings" tab, and try to add a warning to see the number recommendations).

The same data could be used to list all the available warnings in our Attribute / Decorator docs. Might be a little tricky to list them all, so might be worth making the list interactive.

**Comment by Minnozz** [comment]
I've been taking a look at this I think a good first step would be to dynamically generate a table containing warning numbers and their description, from the data in `WarningFlagDescription.res`. Copying them is also an option, but this increases the risk of multiple lists getting out of sync.

However, I don't immediately see where/how I would add a documentation page / section written in ReScript.

- Should I define a component somewhere and reference it in an `.mdx` file?
- What is the best location for this table? You suggested the [Attribute (Decorator)](https://rescript-lang.org/docs/manual/latest/attribute) page, but I would (also) expect them at [the `warnings` section of the build configuration](https://rescript-lang.org/docs/manual/latest/build-configuration#warnings). A third option is the [`@@warning`](https://rescript-lang.org/syntax-lookup) page of the syntax lookup, which does not exist yet. Or maybe a separate page that is linked from all locations?

**Comment by Minnozz** [comment]
Just to get things going, I've created #395. Let me know which direction you want to take this.
