### ISSUE TITLE
Add Js.Json.deserializeUnsafe and Js.Json.serializeExn to the docs

### ISSUE THREAD

**Issue by kevanstannard** [rescript-association/rescript-lang.org#208]
It looks like `Js.Json.deserializeUnsafe` and `Js.Json.serializeExn` are not currently in the docs.

https://rescript-lang.org/docs/manual/latest/api/js/json

Should they be added? Or perhaps intentionally omitted?

**Comment by ryyppy** [comment]
i am not sure tbh, these functions were prematurely added and IMO it's not entirely clear if it's a api that should be used... but if you find it useful, I'd be willing to review a PR

**Comment by kevanstannard** [comment]
Thanks @ryyppy 

I did see these mentioned in the forum a few weeks back, which prompted me to open the ticket, but I'm happy to be guided by the recommendation of you and the team.

Feel free to close this ticket if you feel more discussion on those functions is needed first.

Alternatively I am happy to document, and perhaps include a note that these functions may change or be removed in a future version of ReScript?

**Comment by ryyppy** [comment]
@kevanstannard yeah, feel free to give it a shot and add a note that this functionality should not be relied on too heavily for two reasons: 1) It is an easy way out for a complex problem and might only work for simple cases and 2) I am not too sure if this functionality should further exist (right now I am pretty sure nobody depends on it, so it's easy for us to remove / change later on).

**Comment by kevanstannard** [comment]
@ryyppy OK if we close this issue now?

**Comment by kevanstannard** [comment]
As discussed in PR, better to leave these undocumented for now.

**Comment by ryyppy** [comment]
@kevanstannard yeah, thanks. Sorry for my slow response times. Gonna be better in the next few weeks!
