### ISSUE TITLE
Configuration Schema: sourceItem type incorrect?

### ISSUE THREAD

**Issue by johnridesabike** [rescript-association/rescript-lang.org#228]
https://rescript-lang.org/docs/manual/latest/build-configuration-schema

Navigate to: sources -> sourceItem -> object

> type enum `dev` `lib`

If you use `"type": "lib"` in `bsconfig.json`, `bsb` fails with this error:

```
Error: type field expect "dev" literal  
For more details, please checkout the schema https://rescript-lang.org/docs/manual/latest/build-configuration-schema
```

I’m not sure if this is an error in the documentation or with the compiler.

**Comment by ryyppy** [comment]
The schema comes from the compiler repo. 
Did you use `lib` before? If it's a regression, we'll move this to the compiler repo

**Comment by johnridesabike** [comment]
I’ve never actually used it before. I only saw it now because I was looking at the schema docs for something else, and noticed the `lib` type which I didn’t recognize.

**Comment by ryyppy** [comment]
right. i guess it's a compiler issue then... will move it there!
