### ISSUE TITLE
Search results should display Git tag/docs version

### ISSUE THREAD

**Issue by jthegedus** [rescript-association/rescript-lang.org#245]
## Problem

A search of `switch` will result in multiple results for seemingly the same thing, but in fact the results are for multiple versions of the rescript docs, this results in having the docs version changed when clicking on the wrong link and not easily knowing you did switch. The desired link is only known if you know the version of the docs you are on AND look at the URL listed by the browser (usually bottom-left of window) on hover.

This issue is amplified by the fact the older docs do not have Rescript syntax and for those who do not understand how or that they need to change the version can be cumbersome and lead to issues trying to understand why following the docs is leading to errors (EG: Rescript using `array<>` syntax over `array()`)

![rescript-docs-search-bug](https://user-images.githubusercontent.com/20798510/110286671-6b806580-8039-11eb-997f-5d7db6a4be19.png)

## Expected

The search should only list results for URLs of the currently selected version of the docs, or also specify the verison clearly in the results.

This may not be easily resolved :shrug: 

PS: Rescript is awesome, thanks for all your work.

**Comment by ryyppy** [comment]
I think we should instruct Algolia to only index the /docs/manual/latest docs here. Probably generating a Sitemap would also help 🤦‍♂️

**Comment by ryyppy** [comment]
Had a look at algolia's comdiguration setup. Notes for myself:

- Relevant start_url config: https://docsearch.algolia.com/docs/config-file/#start_urls
- Relevant config json for our website: https://github.com/algolia/docsearch-configs/blob/master/configs/rescript-lang.json
