### ISSUE TITLE
Difference Between ReScript Double-Quote String Literal and JS String

### ISSUE THREAD

**Issue by imjoshellis** [rescript-association/rescript-lang.org#280]
I was just reminded that the first time I tried a non-supported symbol in a double-quote string literal, I got _very_ confused why it wasn't working.

I'm sure other JS devs would assume like me that strings work _exactly_ like JS strings because [the overview](https://rescript-lang.org/docs/manual/latest/overview#string--character) simply says "Same" and there's no reason for us to assume otherwise. A note that explains it's not _quite_ the same would be nice, similar to [the note on Int/Float](https://rescript-lang.org/docs/manual/latest/overview#number). 

I realize that "Proper unicode handling" is mentioned on [Primitive types](https://rescript-lang.org/docs/manual/latest/primitive-types#string) in the part about backticks, but I still think it would be helpful to have it mentioned exactly what the double-quote syntax _does_ support.

**Comment by bobzhang** [comment]
indeed, the current Unicode handling is not ideal. We are working to unify the double quotes and backtics

**Comment by imjoshellis** [comment]
> indeed, the current Unicode handling is not ideal. We are working to unify the double quotes and backtics

I really don't mind there being a difference if there's a reason for strings to work this way. 

I just want documentation so I (and other newcomers) can understand and predict the behavior of quote. 

Without knowing the difference, I'm starting always using backtick because it appears safer and more predictable

**Comment by ryyppy** [comment]
@imjoshellis yeah I'd be open for an extra note for unicode support on the overview

**Comment by fhammerschmidt** [comment]
unicode is supported in both "" and \`\` strings now
