### ISSUE TITLE
Error: can not handle multiple files

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [rescript-association/rescript-lang.org#286]
Hi

I tried to run npm run bs:start in https://github.com/rescript-association/rescript-lang.org 

The error is
```
bsb: [21/318] src/Playground.cmi
FAILED: src/Playground.cmi
can not handle multiple files
```
This error appears for multiple other files.
What could be the issue?

**Comment by ryyppy** [comment]
Related forum thread: https://forum.rescript-lang.org/t/error-can-not-handle-multiple-files/1368/5

**Comment by ryyppy** [comment]
I think this issue should be solved now. If it's not, please reopen the issue 👍
