### ISSUE TITLE
Stdlib doc block parsing needs to change

### ISSUE THREAD

**Issue by chenglou** [rescript-association/rescript-lang.org#309]
Now that we use markdown for stdlib docblocks (see https://github.com/rescript-lang/rescript-compiler/pull/5095), our parsing of the api docs pages will need to change. Thankfully mostly simpler.

- This only applies to `Belt` and `Js`. `Pervasives` isn't touched.
- Most semantics are still preserved, except
  - `{!MyModule.myValue}` links
  - Headers. Will have to think about this.

**Comment by fhammerschmidt** [comment]
@aspeddro do you know if this is still relevant?

**Comment by aspeddro** [comment]
I don't think it's relevant.
