### ISSUE TITLE
Add DevITjobs as a user

### ISSUE THREAD

**Issue by MariaAbadi** [rescript-association/rescript-lang.org#314]
This is a follow-up on: https://github.com/reasonml/reasonml.github.io/pull/721 where @ryyppy suggested that I open an Issues here instead 😊

**Comment by ryyppy** [comment]
Thanks. Will follow up with you as soon as we got our landing page live.

**Comment by MariaAbadi** [comment]
@ryyppy I see the landing page is now live (https://rescript-lang.org), could you please add us as well? :)

**Comment by ryyppy** [comment]
Sure! i am a little short on time to do the actual svg manipulations, could you create a PR following the instructions noted [here](https://github.com/rescript-association/rescript-lang.org) and I will be happy to merge it!

**Comment by MariaAbadi** [comment]
@ryyppy thanks for the hint - added as you suggested :)
https://github.com/rescript-association/rescript-lang.org/pull/502
