### ISSUE TITLE
API docs (future): Generate markdown from inline comments

### ISSUE THREAD

**Issue by ryyppy** [rescript-association/rescript-lang.org#359]
We are currently in the process building the tools for extracting doc headers from ReScript files. The working branch for the extractor can be found [here](https://github.com/rescript-lang/syntax/tree/experimental-docgen).

ReScript doc headers will essentially be plain markdown text, so there will be no special processing on the contents of the docs. Our future docgen binary extracts all this information in a processable JSON format, and maybe also in a markdown compatible format (to skip the userspace transformation step).

When this binary is able to parse and collect all stdlib functionality, we need to do the following tasks to be able to generate all the API docs for our website:

- Transform all doc headers of every stdlib / belt / pervasives module into ReScript compatible markdown + example code
- Extract all the data with our docgen
- Wire up the resulting data in our website infrastructure (with an eventual transformation step in between)

**Comment by Minnozz** [comment]
Can you use help with this? I'm not sure if I can contribute given that I have no OCaml experience, but I would love to have better API docs. For instance, I recently discovered `Belt.Array.joinWith` exists while it is not mentioned [in the API docs](https://rescript-lang.org/docs/manual/latest/api/belt/array).

**Comment by ryyppy** [comment]
If you are keen on helping out, all the extraction logic is located in [this file](https://github.com/rescript-lang/syntax/blob/experimental-docgen/src/resdoc_cli.ml). 

Here are some basic instructions to get things going:
- Clone the project, checkout the `experimental-docgen` branch
- Install ocaml `4.06.1`
- Run `make lib/resdoc.exe` -> This will build our `src/resdoc_cli.ml` executable

Currently, the tool actually extracts most of the information we care about from `resi` and `mli` files. Like this:
`./lib/resdoc.exe -file doc_stuff/belt_Array.mli > output.json`

What's missing:
- Basically the same extraction logic for `ml` (implementation files) -> Should be very similar, but probably will require iterating on different parsetree structures
- Also we'd like to experiment with a flag to expose plain markdown instead of `json` (but maybe not even needed since we can easily transform json via JS ourselves)

**Tips:**
- OCaml 4.06 Parsetree module docs: https://sanette.github.io/ocaml-api/4.06/type_Parsetree.html
- I actually streamed two extensive dev sessions on the `resdoc` tool [here](https://www.youtube.com/watch?v=tKTFjFuQI0Y) and [here](https://www.youtube.com/watch?v=LP6Ly4HmS2A), in case you want to understand how all of this works

**Comment by ryyppy** [comment]
> For instance, I recently discovered Belt.Array.joinWith exists while it is not mentioned in the API docs.

Ah, for this one you can also just submit a PR with the relevant changes in the `Belt.Array` markdown file

**Comment by Minnozz** [comment]
Thanks a lot for the detailed notes! I'm going to take a look at it and see what I can contribute.

**Comment by Minnozz** [comment]
@ryyppy Turns out diving into the compiler internals of the language you're trying to learn is hard 😅

I started out by just adding `.ml` to the match arm that uses `Res_driver_ml_parser` to parse the file, and this results in a [`Syntaxerr`](https://ocaml.org/api/compilerlibref/type_Syntaxerr.html). I would like to print this syntax error and the corresponding [`Location.t`](https://sanette.github.io/ocaml-api/4.06/Location.html#TYPEt) so I can see what I have to fix next, but I'm a bit lost. Do you think you could get me started with that?

**Comment by Minnozz** [comment]
I've started a Draft PR where I'll try to work on this.

**Comment by Minnozz** [comment]
@ryyppy I've added support for .ml and .res files in https://github.com/rescript-lang/syntax/pull/442.

There may be a few Ast types left that we should add.

**Comment by ryyppy** [comment]
@Minnozz good job! will have a look

**Comment by fhammerschmidt** [comment]
This is done now! 🎉
