### ISSUE TITLE
Complete documentation for Attributes (Decorators)

### ISSUE THREAD

**Issue by mindplay-dk** [rescript-association/rescript-lang.org#382]
The documentation for JSX describes a syntax transform with an `@JSX` attribute/decorator.

The documentation for attributes/decorators, however, describes only a built-in set of what must be compiler directives?

Your description of the JSX feature specifically states that, similar to JSX for JS, this feature wasn't purpose-built for React - that it's possible to use the JSX feature for other things?

There must be more to the story?

Since it's possible to implement the `@JSX` attribute as part of your React library, presumably it's possible to write your own attributes, or an alternative JSX transform?

Is the documentation in this area incomplete, or does the language itself not have this feature yet?

If not, do you plan on exposing this (presumably native OCaml?) feature within the ReScript language itself?

**Comment by fhammerschmidt** [comment]
It's now possible to introduce your own JSX transforms, and it is documented here: https://rescript-lang.org/docs/manual/latest/jsx#generic-jsx-transform-jsx-beyond-react-experimental
