### ISSUE TITLE
Back button behaviour in Syntax lookup

### ISSUE THREAD

**Issue by mellson** [rescript-association/rescript-lang.org#383]
When I open something in the excellent Syntax lookup I would expect that the back button brings me back to the overview.
But right now you need to click the `X` to close the popup, pressing the back button will bring you to the page you visited before the syntax page.

Example: https://cln.sh/AcT8y6

Not a major issue, maybe it's just me who thinks this is weird?

**Comment by Minnozz** [comment]
I've implemented a fix for this in #385 (not merged yet).

**Comment by mellson** [comment]
Nice, thanks @Minnozz 👏

**Comment by fhammerschmidt** [comment]
This one got fixed in #445
