### ISSUE TITLE
Document `Node` module

### ISSUE THREAD

**Issue by wontheone1** [rescript-association/rescript-lang.org#401]
Background:

I was looking for a way to read a text file synchronously. Googling and ending up places like this [NPM] package(https://github.com/sikanhe/reason-nodejs).

In reality what I wanted was already there out of the box in `Node` module. (`let input = Node.Fs.readFileAsUtf8Sync("input/Week1/Year2020Day3.txt")`

Without docs mentioning the `Node` module on [the official doc](https://rescript-lang.org/docs/manual/latest/api), it's really hard to discover.

Suggestions:

We could at least start by mentioning the existence of module and some WIP documentation page. As long as template is there, I think it'll be easier for people to make PR to fill in the missing docs.

**Comment by ryyppy** [comment]
Related to #359

**Comment by fhammerschmidt** [comment]
The node module is deprecated now (use https://github.com/TheSpyder/rescript-nodejs instead)
