### ISSUE TITLE
Add production user logo TurboRoof 

### ISSUE THREAD

**Issue by vasco3** [rescript-association/rescript-lang.org#402]
At Turboroof.com we use ReScript for our ecommerce and internal tools.

you can add our logo as a production user
![logo](https://user-images.githubusercontent.com/804301/123436450-41c15f00-d594-11eb-9fe8-6c0f56e199e7.png)

**Comment by ryyppy** [comment]
Do you have a black / white svg version of the logo as well?

**Comment by vasco3** [comment]
yep, here it goes

![logo-black](https://user-images.githubusercontent.com/804301/133789400-b94f5935-cf23-48ba-a7be-53211adcf6c5.png)

**Comment by ryyppy** [comment]
Hey! Just trying to pick that up again... could you send a `.svg` (not `.png`) and eventually already color it with the color `#979AAD`? Then it would be easy to just drop it in.

**Comment by vasco3** [comment]
@ryyppy here it goes!
![turboroof-logo-svg-gray](https://user-images.githubusercontent.com/804301/152241417-28d29ea0-9a1b-4d39-98ef-4abb39c9deef.svg)

**Comment by ryyppy** [comment]
Thanks. Added!

**Comment by vasco3** [comment]
we use rescript in our e-commerce https://tienda.turboroof.com and some internal apps
