### ISSUE TITLE
Should the `og:site_name` meta tag be "ReScript Documentation" for all of the site?

### ISSUE THREAD

**Issue by hoichi** [rescript-association/rescript-lang.org#403]
The `og:site_name` meta tag is currently "ReScript Documentation" everywhere, including the home page and the blog. Looks weird in the previews, e.g., [in Discourse](https://forum.rescript-lang.org/t/ann-roadmap-2021-new-landing-page/1910):

![image](https://user-images.githubusercontent.com/3592345/123443512-a2758980-d5de-11eb-9839-6cc33afc392d.png)

**Comment by ryyppy** [comment]
How should we improve it, and how should it behave on all the different sections within the website?

**Comment by hoichi** [comment]
Here's what I currently see (besides the titles that make sense to me):

	| Path                    | Title                                   |
	| ----------------------- | --------------------------------------- |
	| /blog                   | Blog \| ReScript Documentation          |
	| /packages               | Package Index \| ReScript Documentation |
	| /docs/manual            | ReScript Language Manual                |
	| /docs/manual/latest/api | ReScript API                            |

So I think the bad apples are currently `/blog` and `/packages`, and I think they should be `ReScript Blog` and `Rescript Package Index` (or `ReScript Packages`) accordingly.

**Comment by ryyppy** [comment]
Changed it to your recommendations. Feel free to open another issue if there's still anything off!
