### ISSUE TITLE
Add production user logo SeaMonster Studios 

### ISSUE THREAD

**Issue by logandeancall** [rescript-association/rescript-lang.org#405]
SeaMonster Studios uses ReScript with & for -

- JAM Stack sites
- Internal Tooling
- Client application development
- Shopify Theme development
- [OSS (old) ReasonML monorepo w/bindings and tools](https://github.com/SeaMonster-Studios/sms-reason)
- [ReScript-Index monorepo](https://github.com/SeaMonster-Studios/rescript-index): Bindings, React Hooks, and React Component. These are compiled for and available to React.js developers.

Feel free to use one of the following, w/e you believe fits the design best.

![SMS-Brand-2020-BLACK-Vert](https://user-images.githubusercontent.com/5152553/123463085-f2812b80-d59f-11eb-8473-b4346412c448.png)
![SMS-Brand-2020-BLACK-Horiz](https://user-images.githubusercontent.com/5152553/123463091-f319c200-d59f-11eb-8aa6-a05287e23f8a.png)

**Comment by ryyppy** [comment]
Hey! Trying to pick this up now but realized that your images are `png`s. I'd need them to be `svg`s though.

I just created some instructions on how to add your company logo to our frontpage [here](https://github.com/rescript-association/rescript-lang.org#adding-a-company-logo-on-our-front-page).

Happy to merge if you send me a quick PR!

**Comment by logandeancall** [comment]
I'll create a PR, thank you.
