### ISSUE TITLE
Evaluate code in playground

### ISSUE THREAD

**Issue by tom-sherman** [rescript-association/rescript-lang.org#414]
The TypeScript playground has this great feature where you can run the generated JS code, would you accept a PR to add a similar UI to the ReScript Playground?

**Comment by tom-sherman** [comment]
I've started hacking around on this, my approach right now is:

- Create an `Eval` module that uses a `Worker` under the hood
- `Eval` exposes a state machine for evaluating code
- Figure out some way of bundling the whole of rescript std lib and including it in the worker file

**Comment by ryyppy** [comment]
> would you accept a PR to add a similar UI to the ReScript Playground?

Yes I would!

> Figure out some way of bundling the whole of rescript std lib and including it in the worker file

That will be the most interesting part. I could take over the pipeline for bundling the right stdlib / compiler files, but I am not sure if we need to generate worker files for each compiler version, or if there's a way to point to a specific bundle file via one single entry point?

**Comment by fhammerschmidt** [comment]
this is now implemented, just without a worker
