### ISSUE TITLE
Any plans for function overload or multi-dispatch?

### ISSUE THREAD

**Issue by al6x** [rescript-association/rescript-lang.org#417]
Hi, I like your approach to build a language leveraging great parts of JS.

Wondering if you have any plans to add 

1) function overload

2) multi-dispatch or extension methods? Basically it's the same as function overload but for multiple modules, so functions with same names defined in different modules would be overloaded properly.

Example

```
let add = (x: int, y: int): int => x + y

let add = (x: string, y: string): string => "hi" ++ x ++ y
```

**Comment by ryyppy** [comment]
Hey!

There are no plans for any of the features described above. This would require certain changes that actually spawned its own research field (check out "modular implicits" in the OCaml sphere).
