### ISSUE TITLE
No scripts in `package.json`

### ISSUE THREAD

**Issue by nikitazdvijkov** [rescript-association/rescript-lang.org#427]
After running `npx rescript init .`, the initialized `package.json` does not have any scripts. Meanwhile, the initialized README specifies scripts `npm run build` and `npm run watch`.

**Comment by ryyppy** [comment]
This needs to be reported in the [rescript-compiler](https://github.com/rescript-lang/rescript-compiler/issues) issue tracker

**Comment by fhammerschmidt** [comment]
with `npm create rescript-app`, the successor of `rescript init`, there are scripts there: https://github.com/rescript-lang/create-rescript-app/blob/master/templates/rescript-template-basic/package.json#L4-L8
