### ISSUE TITLE
ReScript web site header doesn't work in Edge on Windows 10

### ISSUE THREAD

**Issue by jmagaram** [rescript-association/rescript-lang.org#447]
This is really weird and think the problem is new because I've been using this website for a couple weeks and haven't noticed any problem. I’m using Edge browser on Windows 10. The header at the top of The ReScript Programming Language (rescript-lang.org) only has links for “Docs” and “API”. The other links aren’t there - moving the mouse over them does nothing. It’s as if the window was much smaller than it really is and those menu items have been removed and put in the `...` menu instead. If I view the website using Chrome or Firefox or (surprisingly) Edge in Private mode, the page header is fine. Edge Version 93.0.961.52 (Official build) (64-bit). Here is what it looks like. Don't know if it matters but I'm signed in to the community forum.

![image](https://user-images.githubusercontent.com/14130251/134038666-d6ae4845-6a05-4e8b-84c3-b07952df3265.png)

**Comment by ryyppy** [comment]
What pixel size does the viewport have in this particular example? Does it show the full navigation when you make the window width larger?

**Comment by jmagaram** [comment]
I’ll check when I get back. But I’m pretty sure it was broken with the web browser maximized Since that is usually how I use the web browser. I took a small screenshot to put in the bug report. You can see that the image doesn’t include an overflow menu which it should if that were the problem.

**Comment by jmagaram** [comment]
Very big screen size, maximized. Here is some of the HTML...

![image](https://user-images.githubusercontent.com/14130251/134089020-c85dfaaa-092a-43a8-8433-2d44e88635bf.png)

**Comment by jmagaram** [comment]
Anyone try to repro this? I'm still having this problem. This is the default browser on Windows 10 - a major issue.

**Comment by ryyppy** [comment]
I recently re-deployed my windows 10 computer to be able to replicate this. Let's see if I can reproduce this.

**Comment by jmagaram** [comment]
The problem went away for me. Using Edge version 94.0.992.38 now. Maybe it was a bug in Edge?

**Comment by ryyppy** [comment]
Yesterday I tried it as well, and it didn't show the bug you described. Not sure what this was about, since the newest Edge version runs on the V8 engine afaik.
