### ISSUE TITLE
pages/docs/react/latest/installation.mdx notes incorrect

### ISSUE THREAD

**Issue by tb01923** [rescript-association/rescript-lang.org#453]
Versions
* rescript: 9.1.4
* react: 17.0.2
* @rescript/react: 0.10.1

this document could be aided a touch: pages/docs/react/latest/installation.mdx

Two recommednations for improvement. First have folks create a ```src``` directory which ```Test.res``` is created-within.  Second a couple small changes to ```bsconfig.js``` to get ```npx rescript``` to run without errors:

1. add a name (e.g. "test-app")
2. add sources folder (e.g. "src")

```
{
  "name": "test-app",
  "bs-dependencies": ["@rescript/react"],
  "reason": {"react-jsx": 3},
  "sources": ["src"]
}
```

**Comment by fhammerschmidt** [comment]
it says "add the following setting to your existing rescript.json". It's not meant to explain how to create an example from scratch which is explained [on the installation page of ReScript itself](https://rescript-lang.org/docs/manual/latest/installation).
