### ISSUE TITLE
Deep equal is not the `==` operator in JavaScript

### ISSUE THREAD

**Issue by uinz** [rescript-association/rescript-lang.org#461]
![image](https://user-images.githubusercontent.com/12208108/143176311-02c14b0b-bef3-4889-8daf-a3754d30158c.png)

The `==` in ReScript is not equivalent to the `==` in JavaScript after compilation

In other words, `Caml_obj.caml_equal` is not equal to `==` in js

**Comment by AlexMoutonNoble** [comment]
Running into this today with my team.
Its possible to do shallow and deep equality between polymorphic variants, for example, where the js representation is variable, and referential control is not clear, desired, (or possible), causing #Y(3) === #Y(3) to be false.

I have made some noise before but it strikes me that strict equality should be removed as an operator and moved to a Js specific location that clearly explains whats going on and prevents its use broadly in the language?

**Comment by weakish** [comment]
see also #503
