### ISSUE TITLE
Playground: incomplete hex escape in string triggers an infinite loop

### ISSUE THREAD

**Issue by kevinbarabash** [rescript-association/rescript-lang.org#463]
Typing the following code into the playground will trigger an infinite loop which stalls the browser:
```
let a = "\x
```
The same happens if you type an empty string first and then add the `\x` inside of it.  I tried reproducing this with bsc.exe but it exits with an appropriate syntax error in both situations so this appears to be playground specific.  I paused the debugger and saw that it's trying to get the char code of some string at a very large index.

<img width="770" alt="Capture d’écran, le 2021-12-04 à 00 15 44" src="https://user-images.githubusercontent.com/1044413/144698198-361a3dcb-abb1-4932-8993-f1fe41ba90e2.png">

**Comment by ryyppy** [comment]
that's probably something for @bobzhang 
Maybe that's an issue with the jsoo'ed output?

**Comment by fhammerschmidt** [comment]
not reproducible anymore
