### ISSUE TITLE
Searching for "Array" results in links that are difficult to distinguish

### ISSUE THREAD

**Issue by kevinbarabash** [rescript-association/rescript-lang.org#465]
<img width="554" alt="Capture d’écran, le 2021-12-12 à 15 39 35" src="https://user-images.githubusercontent.com/1044413/145728781-b58f2bd4-d72a-459f-acca-fc64e9ff1ce3.png">

After clicking on four of the links it also looks like two of them were duplicates.

**Comment by ryyppy** [comment]
Ah yes, a kinda old issue I didn't get around with, but would be glad if someone could have a stab at it.

I made a note in a similar issue here: https://github.com/rescript-association/rescript-lang.org/issues/245#issuecomment-798914943
