### ISSUE TITLE
Feature request : Standalone interpreter command and repl 

### ISSUE THREAD

**Issue by shishini** [rescript-association/rescript-lang.org#467]
I discussed this point on the forum 
https://forum.rescript-lang.org/t/some-thoughts-on-community-building/1474/42

I think having a stand alone commands
```
resx            # rescript execute to run script
respl          # rescript repl
resx -repl  # different command to enter repl
```

can help new comers learn rescript, before jumping into web development

**Comment by ryyppy** [comment]
Due to technical limitations, we are not going to implement a repl.

The closest we will get is have runtime evaluation on the playground, which is currently being discovered by some community members.
