### ISSUE TITLE
Docs Design: Decreasing the line-height on the left-side menu in the Api Docs

### ISSUE THREAD

**Issue by peterpme** [rescript-association/rescript-lang.org#47]
After experimenting around a bit I felt like having the line-height smaller (putting every item closer together) was easier to read on the eyes.

The suggested differences:

before (current way):
<img width="285" alt="image" src="https://user-images.githubusercontent.com/1211905/89453302-a8435180-d724-11ea-96b9-750ea5541b29.png">

after:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/1211905/89453313-ac6f6f00-d724-11ea-87e0-f0417ffe245c.png">

**Comment by chenglou** [comment]
Finally, design-minded issues... thanks!

**Comment by ryyppy** [comment]
the layout will be revisited (yet again) when we allocated new design resources somewhere in March 2021

**Comment by fhammerschmidt** [comment]
this looks better now imo
