### ISSUE TITLE
Documentation question: What is rescript's equivalent for JS then() method?

### ISSUE THREAD

**Issue by marek-lach** [rescript-association/rescript-lang.org#473]
Essentially, what's ReScript's equivalent syntax for handling asynchronous, or in succession operations?

**Comment by ryyppy** [comment]
If you are asking for a syntax equivalent ala `async / await`, then there's none. The recommendation is to stick to the Promise bindings, as described in the docs for now.

**Comment by oh-dev-life** [comment]
@ryyppy  just want to ask, why shouldn't we add async await syntax?

**Comment by cristianoc** [comment]
That comment predates the existence of async-await in the language.

**Comment by cristianoc** [comment]
Technically speaking, it still does not exist. But it will as soon as 10.1 is released officially.
