### ISSUE TITLE
Extra bullet points in "Polymorphic Variant" documentation

### ISSUE THREAD

**Issue by parke** [rescript-association/rescript-lang.org#474]
Fyi, there are two extra bullet points on this page:  
https://rescript-lang.org/docs/manual/latest/polymorphic-variant

On the above page, there is an extra bullet point above each of the following items:
-  `It's also harder to refactor poly variants. Consider this:`
-  `You might lose some nice pattern match checks from the compiler:`

If you don't see the extra bullet points in your browser, please let me know and I will attach a screen shot.

The source for the above page seems to be here:  
https://github.com/rescript-association/rescript-lang.org/blob/master/pages/docs/manual/latest/polymorphic-variant.mdx

The extra bullet points **do not appear** in the source when viewed on Github.

Maybe the extra bullet points are the result of a glitchy Markdown converter somewhere in the production chain?

Given that the extra bullet points do not appear when the page is viewed at Github, I am not able to submit a PR.

**Comment by ryyppy** [comment]
I think the trick is to not make any newline inbetween bullet points. There's currently some Markdown logic bug that will interpret the newline weirdly
