### ISSUE TITLE
Infinite loop from blocked request

### ISSUE THREAD

**Issue by beardedsakimonkey** [rescript-association/rescript-lang.org#498]
Hi, when I try to access rescript-lang.org/ the page stays blank and my browser makes an infinite loop of requests.
Here's a screenshot of how it looks.
![Screen Shot 2022-03-03 at 10 45 44 PM](https://user-images.githubusercontent.com/54521218/156713620-72d7c522-c44f-4d0e-bb16-c2af5898ad5a.png)

It seems like one request is being blocked (I'm using Firefox with uBlock Origin with 3rd party scripts blocked by default), and that seems to cause the issue.  It would be great if this could be handled more gracefully.

Thanks!

**Comment by ryyppy** [comment]
Related to #528
