### ISSUE TITLE
Is it possible to implement something like type classes from purescript?

### ISSUE THREAD

**Issue by krzysztofpniak** [rescript-association/rescript-lang.org#512]
Hi, I would like to implement something like:

`map :: forall f a b. Functor f => (a -> b) -> f a -> f b`

and use it with any type that has `map` implemented, ie. Maybe, List, Either

**Comment by woeps** [comment]
Hi,
A "Functor" in rescript is: a function, taking one (or several) module and returning a new module.
Here is an example: https://rescript-lang.org/try?code=LYewJgrgNgpgBAFwJ4Ad4FkCGLMCNZwC8cA3gFByKrwIA8A5JgHwVywJzDYBccAFHUZMANHEZEmY3AEoJiBrhYBfMmQD0axAAsAlgGc4AY0wA7OLngnMwGGDimkCXSYDmZUJAIAxCCcMIQACcifnReLBx8GFlCSXJKdjgAMxCADzlUgFomdAA6LhQ+VPoMkrUAKjgdMBgTBB1kZN9-HRAzcrVpMhV3cGgMTCQLEPiqNHkhEJAUeraGZlZEgpCAIRgoBFyAeRnWk3zsbtUPfrgAYUCYTARbFaQfPwDg4gf-IL4sIeiyIA

Typeclasses are not really idiomatic in rescript and often result in a (more) convoluted compiled js.  
In my given example you a see, that you need a `module type`, all modules you want to use adhere to. But not all modules use the convention of a `type t<'a>`:
`Belt.Option` does not use a `type t` at all.
Furthermore `Belt.Result` also contains a `map` function but operates on a `type t<'a, 'b>`. (2 type parameters). Which is not compatible with the module type specified in the example.

Finally, there is often a solution, which may not seem that generic but models your goals in a more descriptive way. Would you mind elobarate a little bit mor, what you want to acomplish?

<details>
<summary>Code example for future reference</summary>

```res
module type Mapable = {
  type t<'a>
  let map: (t<'a>, 'a => 'b) => t<'b>
}

// this can be named anything
module Functor = (M: Mapable) => {
  let f = x => x->M.map(x' => x' /* identity function */)
}

module Maybe = {
  type t<'a> = option<'a>
  let map = Belt.Option.map
}

module CreatedByFunctor = Functor(Maybe)
```

</details>

**Comment by ryyppy** [comment]
Hey! Please use the [ReScript Forum](https://forum.rescript-lang.org) for user related questions. This issue tracker is about technical / content related issues for the ReScript documentation platform.

Thanks!
