### ISSUE TITLE
Failed start this project in my local environment.

### ISSUE THREAD

**Issue by Mng12345** [rescript-association/rescript-lang.org#522]
![image](https://user-images.githubusercontent.com/21278900/169685375-2b12a781-961b-4266-9de7-1c0cb5d2f2ff.png)

The index_data directory is empty.
![image](https://user-images.githubusercontent.com/21278900/169685397-a1476dc2-6da3-487d-aaa4-7a8e62e12e78.png)

**Comment by ryyppy** [comment]
Did you do an initial ˋnpm run update-indexˋ as stated in the README?

**Comment by Mng12345** [comment]
Yes, it is also failed for the same reason.
![image](https://user-images.githubusercontent.com/21278900/169949589-5ae3bf1b-0d0f-4052-baf2-103618299a9e.png)

**Comment by ryyppy** [comment]
can you run only `node scripts/extract-indices.mjs` and see what the output is?

I never tried building the project on Windows, so maybe it's a Windows filesystem / process spawning thing?

**Comment by ryyppy** [comment]
You might need to reduce the problem within this script.. maybe i am not using platform independent path separators or something similar.

**Comment by Mng12345** [comment]
Yes. just because the __dirname is not exists in ES module scope, and then it is created by URL, the path it presents is wrong on windows.
![image](https://user-images.githubusercontent.com/21278900/169964942-5d450c93-1f8e-4396-94b9-44ee658414f7.png)
![image](https://user-images.githubusercontent.com/21278900/169964973-59f6eebe-91a8-40e8-9596-1e43a3ea8e96.png)

**Comment by Mng12345** [comment]
I have fixed it by this.
![image](https://user-images.githubusercontent.com/21278900/169965535-6a7aa9f3-17a5-47b2-867f-4fa22bfd431a.png)
But got the another problem.
![image](https://user-images.githubusercontent.com/21278900/169966735-1a4d5f5c-31e7-4fa2-918f-64cbde27c440.png)
![image](https://user-images.githubusercontent.com/21278900/169966763-ea892ab7-8d7b-4b8f-b078-76233d219808.png)

**Comment by Mng12345** [comment]
I have fixed it all by replace every `__dirname` with this anoymous function...... Now it is running normally.

**Comment by Mng12345** [comment]
The __dirname above is not correct, i add a platform check for windows.
![image](https://user-images.githubusercontent.com/21278900/170046933-bd20b855-e011-4ada-b5f8-8a6dfcc9ada4.png)
