### ISSUE TITLE
Allow .bs flag on output suffix for cjs, mjs?

### ISSUE THREAD

**Issue by AlexMoutonNoble** [rescript-association/rescript-lang.org#538]
Hi Patrick
Maybe the wrong repo*, but i notice that the compiler doesnt allow the .bs flag when using .cjs output suffix.
Can We add allowance for this?  The bs bit has been very helpful in porting files from rescript, and trying to sort out cjs/es6 migration these output files break our existing ".bs" imports and otherwise collide with the existing js files in suffixless import.

Thanks
Alex

* a quick search showed this enum in a json schema here.

**Comment by nkrkv** [comment]
The context: https://forum.rescript-lang.org/t/why-there-s-no-bs-mjs-suffix-option-in-bsconfig-json/3697

**Comment by fhammerschmidt** [comment]
`.bs.cjs` is supported for a while now
