### ISSUE TITLE
Document API change in ReScript 10.0.0

### ISSUE THREAD

**Issue by harry-xm** [rescript-association/rescript-lang.org#551]
`pages/docs/manual/latest/api/js/string-2.mdx` and `string.mdx` should be updated to reflect breaking API change.

---

In `rescript@9.1.4`, function signature of `Js.String2.match_` is `(Js.String2.t, Js.Re.t) => option<array<Js.String2.t>>`.

In `rescript@10.0.1`, the function signature has one more nested `option<>` as follows.

```
(
  Js.String2.t,
  Js.Re.t,
) => option<array<option<Js.String2.t>>>
```

Copied from https://github.com/rescript-lang/rescript-compiler/issues/5643.

**Comment by danielo515** [comment]
I was going crazy about this. Thanks for the bug report
