### ISSUE TITLE
Automate playground compiler versions updates

### ISSUE THREAD

**Issue by ryyppy** [rescript-association/rescript-lang.org#565]
Currently the playground fetches its compiler / react bundles from our CDN, but we need to manually adjust the `CompilerManagerHook` module whenever a new playground version has been released.

This is tedious. Ideally we want to automate the playground bundle generation process for each proper version release. The website should update itself whenever a new playground version has been uploaded.

## Proposed Architecture:

**Playground / rescript-lang.org changes**
- Use `getStaticProps` to generate the available versions data on incremental builds / revalidations
- Within the `getStaticProps` logic, query `https://cdn.rescript-lang.org/` and enumerate all `vX.X.X` versions
  - versions tagged as `alpha` or `beta` release should be separated in "experimental versions"
  - On initial load without version query param, the playground should load the latest official version
- Pass the information down to the playground page and introduce the data in the version select dropdown
- Introduce a protected revalidation route, as stated in the NextJS docs: https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#using-on-demand-revalidation
- Introduce a secret for the revalidation logic and store it in the rescript-lang.org secrets

**ReScript compiler repo changes:**
- Store the revalidation key as a secret in the rescript-compiler repo
- In the `playground/update_bundle.sh` script, run the revalidation url with the stored secret after the newest bundle has been uploaded

**Comment by aspeddro** [comment]
> On initial load without version query param, the playground should load the latest official version

I'm working on it and I'm making a call to https://registry.npmjs.org/rescript/latest to get the latest stable version and load the compiler, but the CDN doesn't have the "10.1.4" version. https://cdn.rescript-lang.org/

Should we update the CDN or is there another way to do this?

**Comment by ryyppy** [comment]
There is no equivalent 10.1.4 release, since we didn't have the chance to generate a JS bundle and it's too much work to backport the necessary infrastructure support.

**Comment by ryyppy** [comment]
By "latest official version", I actually meant the latest version that is acailable on the CDN that is not an alpha / beta version.

**Comment by fhammerschmidt** [comment]
This worked flawlessly when ReScript 11 was published. Closing...
