### ISSUE TITLE
JSX page needs overhaul

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-association/rescript-lang.org#589]
https://rescript-lang.org/docs/manual/latest/jsx

* it still mentions ReasonReact
* it even links to the old ReasonReact docs
* children spread is not necessary anymore 
* the "JS Output" is often not the real final JS output

Overall I am also not sure if the desugared / ppxed snippets should be there anyway.

Of course now with JSX4 landing, it will be adapted anyway, those were just the things that stand out like a sore thumb to me.

**Comment by mattdamon108** [comment]
IMHO, I couldn’t find the fine reason to state the desugared expressions by ppx.
I think it is better to explain what `@react.component` is doing for.

**Comment by cristianoc** [comment]
The whole `@JSX` description can go as `@JSX` has now become an implementation detail that can just disappear now that the parser is vertically integrated in the compiler.

**Comment by mattdamon108** [comment]
> I think it is better to explain what `@react.component` is doing for.

Nope. I guess `@react.component` is not necessary to be explained on the JSX page. It is more like to be stated on the ReScriptReact page.
