### ISSUE TITLE
Type errors, Warnings shown in the ReScript Playground for snippets in the Exceptions documentation page

### ISSUE THREAD

**Issue by kamweti** [rescript-association/rescript-lang.org#600]
Actual

- Go to https://rescript-lang.org/docs/manual/latest/exception
- Run the first code example in the ReScript playground.
- See the type error in Javascript tab
- See `unused variable items` warning in the Problems tab

Expected

- Compiler should finish without errors/warnings

Beginners are stumped as they cannot try the examples listed and instead spend time having to fix the code.

Remedy 

- Code examples must contain all required/dependent Types/Methods/Externals  before running in the Rescript Playground

**Comment by cristianoc** [comment]
That code tab uses a ` ```res ` block, but needs a ` ```res prelude` block so it gets type checked when tests are run.
Feel free to open a PR.

**Comment by kamweti** [comment]
@cristianoc thanks for the response, how do we best showcase an example that is dependent on a external js file, such as this one in the Catching Javascript Errors page?

https://rescript-lang.org/docs/manual/latest/exception#catching-js-exceptions

here we require an external javascript file containing the `someJSFunctionThatThrows` method
