### ISSUE TITLE
Why are to and downto not reserved words?

### ISSUE THREAD

**Issue by kamweti** [rescript-association/rescript-lang.org#609]
`to` and `downto` can be used in a for loop as indicated [here](https://rescript-lang.org/docs/manual/latest/control-flow#for-loops)

but they are not listed as [reserved words](https://rescript-lang.org/docs/manual/latest/reserved-keywords)

why is this?

**Comment by cristianoc** [comment]
Because they are not keywords, this is valid:

```res
let do = 10
```

There is enough context in the language to understand their use in for loops without forbidding the use as variables.

**Comment by kamweti** [comment]
I see, thanks for explaining.
