### ISSUE TITLE
Migrate from JSX v3’s doc redirection error

### ISSUE THREAD

**Issue by JiaeK** [rescript-association/rescript-lang.org#641]
Currently, switching between documentation versions using sidebar (v.0.10.0 to v.0.11.0) of [Migrate from JSX v3](https://rescript-lang.org/docs/react/latest/migrate-from-v3)’s doc gives 404 errors like [the below](https://rescript-lang.org/docs/react/v0.10.0/migrate-from-v3):
![redirection prob](https://user-images.githubusercontent.com/78751231/211285713-63fd4649-db4d-4d93-a132-79e0cc6c3486.png)

That is, Migrate from JSX v3’s doc and the former version of it, AKA [Migrate from ReasonReact](https://rescript-lang.org/docs/react/v0.10.0/migrate-from-reason-react)’s doc, have redirection problems.

**Comment by cristianoc** [comment]
@mununki I guess this is because the paths are different: `migrate-from-reason-react` vs `migrate-from-v3`.
Would it be possible to choose a single file name for that doc, so routing does not change across versions, but keeps the same title as the user sees now?

**Comment by cristianoc** [comment]
E.g. this: https://github.com/rescript-association/rescript-lang.org/pull/643
