### ISSUE TITLE
Update ReScript users section

### ISSUE THREAD

**Issue by gkz** [rescript-association/rescript-lang.org#659]
messenger.com no longer uses ReScript. I believe [OurUsers.res](https://github.com/rescript-association/rescript-lang.org/blob/master/src/common/OurUsers.res) should be updated to remove both Messenger and Facebook entries.

**Comment by chenglou** [comment]
Hi George.

Thanks. I reached out to some old teammates and it indeed seems like ReScript is being pushed out. We'll update the site accordingly. Tech choices can be influenced by various factors, though we respect the decision made. Best of luck with Flow.
