### ISSUE TITLE
Interesting similar approach in F# with Feliz

### ISSUE THREAD

**Issue by jkone27** [rescript-association/rescript-lang.org#669]
https://zaid-ajaj.github.io/Feliz/ maybe interesting to compare also the .NET ocaml implementation in F# via Fable and Feliz

**Comment by ryyppy** [comment]
Thanks for letting us know, but I am not sure how and where this would be useful for the documentation? Or are you talking about comparing it for our own development purposes? If so, it's better to post such information on our forum: forum.rescript-lang.org

**Comment by jkone27** [comment]
F# is also an OCAML-derived language mostly : ) but that works full-stack also for aspnetcore backends, would be nice to have a comparison article or review indeed, if someone could be interested! Cheers, have a great day! 🌞

**Comment by fhammerschmidt** [comment]
Fable is awesome! But this is out of scope for the docs. If somebody is interested, they can publish a comparison on their own blog or dev.to or something.
