### ISSUE TITLE
Playground action buttons are too far on the right

### ISSUE THREAD

**Issue by ryyppy** [rescript-association/rescript-lang.org#691]
<img width="2547" alt="image" src="https://github.com/rescript-association/rescript-lang.org/assets/1121889/e3ce603b-f223-4f7b-8dad-e03aab3a7ebf">

I got a little surprised how far on the right the "Format" and "Copy Share Link" buttons are.
They should probably stick to the left-hand side instead, so they are easy to see?

\cc @aspeddro

**Comment by aspeddro** [comment]
See #692

**Comment by fhammerschmidt** [comment]
Close?
