### ISSUE TITLE
Inconsistent Array behavior

### ISSUE THREAD

**Issue by pdewacht** [rescript-association/rescript-lang.org#712]
The [installation page](https://rescript-lang.org/docs/manual/latest/installation) tells new users to start a project by cloning [rescript-lang/rescript-project-template](https://github.com/rescript-lang/rescript-project-template).

This template uses the Core library and I think as a result arrays no longer behave [as documented](https://rescript-lang.org/docs/manual/latest/array-and-list): in the example on that page, `myArray[0]` would return `Some("hello")` rather than `"hello"`.

I have no opinion on how this should be resolved, but the current situation is rather confusing for new users. If new projects are supposed to use Core, then the documentation should describe the Core behavior.

**Comment by fhammerschmidt** [comment]
This is fixed now.
