### ISSUE TITLE
Unnecessary cases created in switch

### ISSUE THREAD

**Issue by bobrovnikov** [rescript-association/rescript-lang.org#728]
Playground: https://rescript-lang.org/try?version=v10.1.2&code=DYUwLgBAzg7glmAxgCwKIA8CGBbADqCAXggAo4A7XAVzAC4IKwBKIgPggG8AoCaeJZA0o1OPXhAD0EiOQD2YOIhAzZEAKwQQ6OFDBQIyEACcQAQjEAfCABY2NyxACMABjsuHjgExvPDgPp2zmIAvlzBQA

Notice how in ReScript I provided 3 specific cases + a default one, while the transpiled code contains much more.

**Comment by zth** [comment]
This should probably be in the compiler repo instead: https://github.com/rescript-lang/rescript-compiler
