### ISSUE TITLE
Package specs are not resepected by the compiler

### ISSUE THREAD

**Issue by TomiS** [rescript-association/rescript-lang.org#745]
It appears that in version `11.0.0-rc.5` the package specs do not work properly (in a monorepo context). If I add
```
  "package-specs": [
    {
      "module": "es6",
      "in-source": true
    },
    {
      "module": "commonjs",
      "in-source": false
    }
  ],
```
into all of the `rescript.json` files in the repo, only the `es6` build is actually being done. `lib/js` stays empty.

The problem can be reproduced by checking out this repo:
https://github.com/Rohea/rescript-color
and by running
```
pnpm i
pnpm build
```

**Comment by fhammerschmidt** [comment]
Two things: 
1. This is a compiler issue, could you [open it there](https://github.com/rescript-lang/rescript-compiler/issues/new)?
2. When you do that, please make it clear if it worked for you with earlier rescript versions.

Thanks.

**Comment by TomiS** [comment]
Uh, sorry. I should have checked the repo better.
