### ISSUE TITLE
Generated file is bs.js or res.js?

### ISSUE THREAD

**Issue by nobodxbodon** [rescript-association/rescript-lang.org#783]
Trying to follow [New Project](https://rescript-lang.org/docs/manual/latest/installation#new-project), in which the last running step is `node src/Demo.res.js`, but the file generated on my local machine is `Demo.bs.js`.

BTW what's `bs` stand for?

**Comment by cknitt** [comment]
"bs" stands for BuckleScript (an early name for the ReScript compiler).

We are currently in the process of finishing the release of v11 and the associated tools.

In the meantime, please try

```sh
npm create rescript-app@next
```
