### ISSUE TITLE
Error during create-rescript-app on Windows 10 PowerShell

### ISSUE THREAD

**Issue by zsombro** [rescript-association/rescript-lang.org#805]
Whenever I try to run "npm create-rescript-app" in PowerShell on Windows 10 I get an "Invalid character" script error after picking out version from the wizard (on attached screenshot). The same thing happens in the regular Windows command line.

I also get a debug log from npm that I have attached to this post. I tried updating Node and npm to the latest version, but it didn't help.

Node v18.6.0
npm 9.6.4

[2024-01-27T21_17_51_228Z-debug-0.log](https://github.com/rescript-association/rescript-lang.org/files/14073865/2024-01-27T21_17_51_228Z-debug-0.log)
![rescript error](https://github.com/rescript-association/rescript-lang.org/assets/2538045/3333a1e4-fc4b-4a0d-b79a-2fb5477e5065)

**Comment by cknitt** [comment]
This repo is for the ReScript documentation website.
Please report issues with `create-rescript-app` to the [create-rescript-app repo](https://github.com/rescript-lang/create-rescript-app) instead.

(I assume you were running "npm create rescript-app", not "npm create-rescript-app"? The latter will not work on any platform.)

**Comment by fhammerschmidt** [comment]
@zsombro as you never created a new issue in [create-rescript-app](https://github.com/rescript-lang/create-rescript-app), I will close this one. Feel free to open a new one there if the issue still exists.
