### ISSUE TITLE
Add more detailed documentation of bs decorators

### ISSUE THREAD

**Issue by smorimoto** [rescript-association/rescript-lang.org#83]
Right now, there's a section that lists them, but information about how to use them is scattered in quite a few places, turning them into hidden knowledge. This will definitely confuse beginners and make them want to go back to their former community.

**Comment by smorimoto** [comment]
Here is the list: https://rescript-lang.org/docs/manual/latest/interop-cheatsheet#list-of-bs-decorators

**Comment by smorimoto** [comment]
Oh, the old version seems to be still here: https://rescript-lang.org/docs/reason-compiler/latest/decorators
If you are looking for such a document, it's recommended to look here for the time being.

**Comment by ryyppy** [comment]
We will revisit this document in a new revised, and easier to navigate version in the future

**Comment by smorimoto** [comment]
That's pretty good. After all, these are the most important part of JavaScript interop, and the fact that documentation about them is still hidden or scattered is a major downside.

**Comment by ryyppy** [comment]
Will be fixed by #111

**Comment by ryyppy** [comment]
Almost all decorators should now be documented in our current Syntax Lookup Widget page:
https://rescript-lang.org/syntax-lookup

Let me know if this is solving your issue, and let us know if you miss any particular decorator.

**Comment by ryyppy** [comment]
Will close this for now. Open any new issues if there's anything important missing!
