### ISSUE TITLE
Add TS interop tutorial with links to GenType

### ISSUE THREAD

**Issue by glebbash** [rescript-association/rescript-lang.org#88]
Just found out about ReScript, looks very promising. But I almost threw it to the trash because I thought there was no TS interop. Shouldn't genType for TS be one of the main parts of Language Manual?

**Comment by ryyppy** [comment]
Yeah at some point there will be proper guides on how ReScript can be properly integrated in TS codebases as well. For now we are still in the process getting the core docs done.

**Comment by danielo515** [comment]
You are almost there! Just add complete instructions on how to use gentype.
This page explains how to use it, but has no reference to install instructions or configuration!!
https://rescript-lang.org/docs/gentype/latest/introduction

It is super frustrating, because as a user you think that there may be something that you are missing or you are just stupid, but no, it is just the 50% of the instructions are on the npm package. Could you consider at least adding a link to the npm package? I thought this was built into reason

**Comment by ryyppy** [comment]
> It is super frustrating, because as a user you think that there may be something that you are missing or you are just stupid, but no, it is just the 50% of the instructions are on the npm package. Could you consider at least adding a link to the npm package? 

Are you aware that the Getting Started section gives all the instructions on how to install and configure it?
https://rescript-lang.org/docs/gentype/latest/getting-started

> I thought this was built into reason
We are not Reason. This is ReScript?

**Comment by danielo515** [comment]
> Are you aware that the Getting Started section gives all the instructions on how to install and configure it?

No I was not. I was not able t find it on the docs searching for Gentype. The introduction was all that I found, there were no link to getting started, I  swear. Thanks for the link. I think I thought the link was for going back to rescript getting started, not that it was a subsection of gentype. 
![image](https://user-images.githubusercontent.com/2270425/129670850-31f0c5c9-e453-4204-8319-199801bca8a7.png)


> We are not Reason. This is ReScript?

I meant rescript, sorry

**Comment by ryyppy** [comment]
Hm, I am not happy with the GenType TOC anyways, so it would probably be worth restructuring the information in a more logical order. Thanks for clarifying!

**Comment by glebbash** [comment]
Docs look much better now. Including the screenshot with location of `genType` docs for reference.
![image](https://user-images.githubusercontent.com/17786588/144051133-5917f610-c2f8-441a-bc34-30d8b0285415.png)
