### ISSUE TITLE
Hiding the top nav on mobile devices feels extremely janky

### ISSUE THREAD

**Issue by kantuni** [rescript-association/rescript-lang.org#899]
The functionality introduced in [Hide top nav on reading docs on mobile](https://github.com/rescript-association/rescript-lang.org/commit/6cb18fb3846ea640f575ef55c2353782be8736ae) feels extremely janky. Please fix the flicker when hiding or showing the top nav.

**Comment by cometkim** [comment]
Can you record it?

**Comment by cometkim** [comment]
please let me know if the problem persists. 
However the feature only uses the transform of an isolated context. I guess it's more likely a different issue.

**Comment by kantuni** [comment]
It looks like #902 fixed it. I can still see the flicker, but very rarely. It might be a good idea to add some leeway before showing the header.

In any case, thank you so much for tackling this so fast!
